# Generated by Django 4.1 on 2022-10-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=80, unique=True)),
                ('content', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
