# Generated by Django 4.1.4 on 2023-03-17 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_product'),
        ('drf', '0003_student'),
    ]

    operations = [
    ]
